### ISSUE TITLE
Module not found: Error: Can't resolve './core/config' in 'D:\Danjavia\projects\sg-covid\node_modules\svelte-speedometer\src

### ISSUE THREAD

**Issue by Danjavia** [palerdot/svelte-speedometer#2]
HI, It´s possible to solve it?

**Comment by palerdot** [comment]
@Danjavia Hi it is being fixed ... Thanks for raising this issue and keep tuned this issue ... In the next 18 hours I will update this issue on the fix ...

**Comment by Danjavia** [comment]
Really thank you!!!! @palerdot I stay tuned!!!

Awesome job!!!

**Comment by palerdot** [comment]
@Danjavia I have fixed this issue in `v1.0.1`. Can you update to this version and see if it fixes your issue?

**Comment by Danjavia** [comment]
Ohh sorry other issue now

can´t resolve d3

**Comment by Danjavia** [comment]
the excat issue is it 

**Module not found: Can't resolve 'd3' in 'D:\Danjavia\projects\sg-covid\node_modules\svelte-speedometer\src'**

**Comment by palerdot** [comment]
@Danjavia I fixed this in `v1.0.2` ... can you try updating and check this issue? I had to move the actual dependencies to `dependencies` field instead of `devDependencies` ...

Please update to `v1.0.2` and see if that fixes your issue ...

**Comment by Danjavia** [comment]
yes off course I'll do right now

**Comment by Danjavia** [comment]
Run perfect right now!!! Thanks a lot @palerdot You´re amazing!

**Comment by palerdot** [comment]
@Danjavia Glad your issues are fixed. I'm closing this issue. Please feel free to open if you face issues again.
