### ISSUE TITLE
Can't get speedometer to load 

### ISSUE THREAD

**Issue by Greg-Owens** [palerdot/svelte-speedometer#24]
Hi,
Cannot even get the basics to work... hope you can help...
Using Svelte...

Error message in browser console is:

Uncaught TypeError: Cannot read properties of undefined (reading 'parentNode')
    at mountGauge (index.mjs:6615)
    at index.mjs:6637
    at run (index.mjs:18)
    at Array.map (<anonymous>)
    at index.mjs:1390
    at flush (index.mjs:723)
    at init (index.mjs:1477)
    at new App (App.svelte:77)
    at createProxiedComponent (hmr-runtime.js:4)
    at new ProxyComponent (hmr-runtime.js:4)

App.svelte is:

<script>
    // import Textfield from '@smui/textfield';
    // import Icon from '@smui/textfield/icon';
    // import HelperText from '@smui/textfield/helper-text';
    import Speedometer from "svelte-speedometer";

    import Card, {
        Content,
        Actions,
        ActionButtons,
        ActionIcons,
    } from '@smui/card';
    import Button, {Label} from '@smui/button';
    import IconButton from '@smui/icon-button';
    import Fab from '@smui/fab';

    import TopAppBar, {
        Row,
        Section,
        Title,
        AutoAdjust,
        TopAppBarComponentDev
    } from '@smui/top-app-bar';

    let topAppBar;
    let search_string = ' ';

</script>

<link
        rel="stylesheet"
        href="https://fonts.googleapis.com/icon?family=Material+Icons"
/>

<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,600,700"/>

<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Mono"/>

<link rel="stylesheet" href="node_modules/svelte-material-ui/bare.css"/>

<style>
    /* Hide everything above this component. */
    :global(app),
    :global(body),
    :global(html) {
        display: block !important;
        height: auto !important;
        width: auto !important;
        position: static !important;
    }

    .bottombar {
        background-color: rgba(227, 245, 216, 0.8);
        height: 58px;
        width: 100%;
        border: 0px;
        color: black;
        bottom: 0;
        position: fixed;
        padding-top: 8px;
    }

    .bottombar-icon {
        padding-left: 20px;
        padding-right: 20px;
        margin-left: 50px;
    }

</style>

<div class="container">
    <TopAppBar bind:this={topAppBar} variant="standard">
        <Row>
            <Section>
                <IconButton class="material-icons">menu</IconButton>
                
                <Title>pifl</Title>
            </Section>
            <Section align="end" toolbar>
                <IconButton class="material-icons bottombar-icon" aria-label="search">search</IconButton>
                <IconButton class="material-icons" aria-label="person">person_outline</IconButton>
            </Section>
        </Row>
    </TopAppBar>

    <AutoAdjust {topAppBar}>

        
        
        
        

    </AutoAdjust>

    <Card>
    <div class="container" style="width:800px;">
        <Speedometer
                width={600}
                value={333}
                segments={5}
                segmentColors={[
    "#bf616a",
    "#d08770",
    "#ebcb8b",
    "#a3be8c",
    "#b48ead",
  ]}
        />
    </div>

    </Card>

    <div class="bottombar">

        <IconButton class="material-icons" aria-label="home">home</IconButton>
        <IconButton class="material-icons" aria-label="lightning">bolt</IconButton>
        <IconButton class="material-icons" aria-label="bulb">tungsten</IconButton>

    </div>

</div>

Any thoughts where to look???

Thanks
Greg

**Comment by palerdot** [comment]
This seems to be a problem with your app code. 

> Uncaught TypeError: Cannot read properties of undefined (reading 'parentNode')

Most likely the parent node is not rendering.

There is no problem with the library itself - eg: https://svelte.dev/repl/c7e2f081bce34508b07265d6d12cca65?version=3.29.4

Please create a minimal svelte repl repro so that you can get a better understanding of where the problem is.

PS: I'm closing this issue since it is not related to the library itself. Please feel free to add details to this thread. I will see if I can throw any light on it.

**Comment by Greg-Owens** [comment]
I am using it from within Meteor - simplified the script to just a single component with the Speedometer in it and still same error...  does it not work within Meteor?  Or do I have to something special?

**Comment by palerdot** [comment]
> does it not work within Meteor?

I have not used it with meteor. In any case without a minimal reproduction repo/repl, it is very difficult to arrive at conclusions.
