### ISSUE TITLE
TypeError: Cannot read property 'parentNode' of undefined

### ISSUE THREAD

**Issue by JojoDz** [palerdot/svelte-speedometer#35]
We're using the speedometer in our app. Thanks for it.

We are unit testing with jest, and when we include the Speedometer in one svelte component, we have the following error : 

```
TypeError: Cannot read property 'parentNode' of undefined 
```
When we follow the stack it leads to `mountGauge` :
```
config = getConfig({
                        PROPS,
                        parentWidth: gaugeDiv.parentNode.clientWidth,
                        parentHeight: gaugeDiv.parentNode.clientHeight
                });
```

So `gaugeDiv` is undefined. We've seen the unit tests of svelte-speedometer, and we don't understand why it fails with our tests.

Do you have an idea why gaugeDiv would not be bound ?

**Comment by palerdot** [comment]
Try rendering the speedometer inside a `div` or any other html element.

Also, pls share your test case if possible to debug this better.

**Comment by palerdot** [comment]
Please reopen with your sample test code in case you are still facing issues.

**Comment by JojoDz** [comment]
Rendering the speedometer inside another html element did not work.
